---
- name: 'Stat base image'
  stat:
    path: '{{ libvirt_default_pool_dir }}/{{ item.import_image_url | basename }}'
  register: stat_base_image
  when: not libvirt__recreate

- name: 'Download image'
  get_url:
    url: '{{ item.import_image_url }}'
    dest: '{{ libvirt_default_pool_dir }}/{{ item.import_image_url | basename }}'
    checksum: '{{ item.import_image_url_checksum }}'
  when: libvirt__recreate or not stat_base_image.stat.exists

- name: 'Set base image'
  set_fact:
    libvirt__base_image: '{{ libvirt_default_pool_dir }}/{{ item.import_image_url | basename }}'
